services:
  bot:
    build: .
    container_name: klutzco-lil-helper
    env_file:
      - .env
    volumes:
      - bot_data:/app/data
    networks:
      - bot-network
    restart: unless-stopped
  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      klutzco-lil-helper
      --interval 300
      --cleanup
      --notification-url discord://{DISCORD_WEBHOOK_TOKEN}
volumes:
  bot_data:
    driver: local

networks:
  bot-network:
    driver: bridge
